# don't build tags, it's redundant
if: tag IS blank

sudo: false
language: node_js
jdk:
  - oraclejdk8

cache: npm

notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '12'
services:
  - xvfb
addons:
  chrome: stable

script:
  - npm run lint
  - npm test
