# don't build tags, it's redundant
if: tag IS blank

sudo: false
language: node_js
jdk:
  - oraclejdk8

cache: npm

notifications:
  email: false
node_js:
  - '10'
  - '12'
services:
  - xvfb
addons:
  chrome: stable

script:
  - npm run lint
  - npm start &   # you might want to use @serenity-js/local-server instead
  - npm test
